services:
  mysql:
    image: mysql:8.0
    container_name: nompay_banking
    environment:
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MYSQL_DATABASE: bank
      MYSQL_USER: application_master
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_bank:/var/lib/mysql

volumes:
  mysql_data_bank:
